# Generated by Django 5.1.6 on 2025-03-04 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='student_parent',
        ),
        migrations.AddField(
            model_name='user',
            name='parent_students',
            field=models.ManyToManyField(to='api.parent'),
        ),
    ]
