# Generated by Django 5.1.6 on 2025-03-01 18:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_alter_group_options_alter_payment_options_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SuperAdmin",
        ),
        migrations.CreateModel(
            name="Superuser",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("api.user",),
        ),
        migrations.AlterField(
            model_name="payment",
            name="month",
            field=models.IntegerField(default=3),
        ),
    ]
