# Generated by Django 5.1.6 on 2025-03-04 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_user_student_parent_user_parent_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='parent_students',
            field=models.ManyToManyField(blank=True, to='api.student'),
        ),
    ]
