# Generated by Django 5.1.6 on 2025-02-23 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0003_room_group_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='lesson_days',
            field=models.CharField(choices=[('1-3-5', 'Odd'), ('2-4-6', 'Even')], default='', max_length=255),
            preserve_default=False,
        ),
    ]
